using MyHospitalCalendar.Core.DTOs;
using MyHospitalCalendar.Core.Services;
using MyHospitalCalendar.Core.Services.Interfaces;
using MyHospitalCalendar.Core.Test.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace MyHospitalCalendar.Core.Test
{
    public class CalendarServiceTest
    {
        private ICalendarService _calendarService;

        public CalendarServiceTest()
        {
            _calendarService = new CalendarService();
        }


        [Fact]
        public void CreateCalendar_1()
        {
            MonthDTO week = new MonthDTOBuilder().WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 5, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 5, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 5, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 6, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 6, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 6, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 7, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 7, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 7, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 7, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 8, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 8, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 9, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 9, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 9, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 9, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 9, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 9, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 10, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 10, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 10, 23, 59, 59)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 11, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 11, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 11, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 11, 16, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 11, 16, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 11, 23, 59, 59)));



            List<PersonDTO> doctors = new List<PersonDTO>();
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Paolo")
                                .WithMaxHours(20));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Gianna")
                                .WithMaxHours(40)
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 16, 0, 0))));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Rodolfo")
                                .WithMaxHours(20));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Simonetta")
                                .WithMaxHours(20));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Luca")
                                .WithMaxHours(40));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Jennifer")
                                .WithMaxHours(40));


            List<ShiftTableDTO> calendar = _calendarService.CreateCalendar(week, doctors);

            Assert.False(calendar.Any(x => x.NoChoice));
        }


        [Fact]
        public void CreateCalendar_2()
        {
            MonthDTO week = new MonthDTOBuilder().WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 1, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 1, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 1, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 2, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 2, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 2, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 2, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 3, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 3, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 3, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 3, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 4, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 4, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 5, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 5, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 6, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 6, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 7, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 7, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 7, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 7, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 8, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 8, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 8, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 8, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 9, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 9, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 9, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 9, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 10, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 10, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 11, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 11, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 11, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 11, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 12, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 12, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 12, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 12, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 13, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 13, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 13, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 13, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 14, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 14, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 14, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 14, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 15, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 15, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 15, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 15, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 16, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 16, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 16, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 16, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 17, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 17, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 17, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 17, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 18, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 18, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 18, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 18, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 19, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 19, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 19, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 19, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 20, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 20, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 20, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 20, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 21, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 21, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 21, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 21, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 22, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 22, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 22, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 22, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 23, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 23, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 23, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 23, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 24, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 24, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 24, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 24, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 25, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 25, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 25, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 25, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 26, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 26, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 26, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 26, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 27, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 27, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 27, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 27, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 28, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 28, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 28, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 28, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 29, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 29, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 29, 20, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 29, 20, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 30, 8, 0, 0)))
                                                    .WithRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 30, 8, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 30, 20, 0, 0))); ;




            List<PersonDTO> doctors = new List<PersonDTO>();
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Odorisio")
                                .WithMaxHours(96)
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 10, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 14, 23, 59, 59)))
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 24, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 28, 23, 59, 59))));

            doctors.Add(new PersonDTOBuilder()
                                .WithName("Arianna")
                                .WithMaxHours(48)
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 20, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 21, 59, 59))));

            doctors.Add(new PersonDTOBuilder()
                                .WithName("Vanessa")
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 23, 59, 59))));
            doctors.Add(new PersonDTOBuilder()
                                .WithName("Diego")
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 5, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 6, 23, 59, 59)))
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 12, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 14, 23, 59, 59)))
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 22, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 23, 23, 59, 59)))
                                .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                        .WithDateStart(new DateTime(2021, 3, 26, 0, 0, 0))
                                                                        .WithDateEnd(new DateTime(2021, 3, 28, 23, 59, 59))));


            doctors.Add(new PersonDTOBuilder()
                               .WithName("Stefano")
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 1, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 8, 23, 59, 59))));

            doctors.Add(new PersonDTOBuilder()
                               .WithName("Roberto")
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 25, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 28, 23, 59, 59))));

            doctors.Add(new PersonDTOBuilder()
                               .WithName("Paolo")
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 1, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 1, 23, 59, 59)))
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 8, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 8, 23, 59, 59)))
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 15, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 15, 23, 59, 59)))
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 17, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 17, 23, 59, 59)))
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 22, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 22, 23, 59, 59)))
                               .WithNotAvailableRoutine(new RoutineDTOBuilder()
                                                                       .WithDateStart(new DateTime(2021, 3, 27, 0, 0, 0))
                                                                       .WithDateEnd(new DateTime(2021, 3, 29, 23, 59, 59))));

            doctors.Add(new PersonDTOBuilder()
                               .WithName("Nicola"));


            List<ShiftTableDTO> calendar = _calendarService.CreateCalendar(week, doctors);

            Assert.False(calendar.Any(x => x.NoChoice));
        }
    }
}
